import { audio } from '../core/audio';
import { drawCat, drawPawPattern, drawSky, roundRect, shape } from '../core/draw';
import { clamp, formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';

class BallCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number;
  private catX = 240; private catY = 500; private ballX = 120; private ballY = 300; private vx = 180; private vy = 125; private caught = 0; private score = 0; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; host.hud.setScore('Поймано', '0'); host.hud.setProgress('Цель', 0, '0 / 12'); host.hud.setStatus('Лови мячик'); host.input.onTap((x) => { this.catX = x; }); }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; const axis = this.host.input.axisX(); const p = this.host.input.pointer; if (axis) this.catX += axis * 320 * dt; else if (p.active) this.catX += (p.x - this.catX) * Math.min(1, dt * 7); this.catX = clamp(this.catX, 50, this.w - 50); this.ballX += this.vx * dt; this.ballY += this.vy * dt; if (this.ballX < 30 || this.ballX > this.w - 30) this.vx *= -1; if (this.ballY < 130 || this.ballY > 520) this.vy *= -1; if (Math.hypot(this.ballX - this.catX, this.ballY - this.catY) < 65) { this.caught += 1; this.score += 20; audio.play('pickup'); this.host.hud.toast('Мяч пойман!'); this.ballX = rand(45, this.w - 45); this.ballY = rand(150, 480); this.vx *= 1.04; this.vy *= 1.04; } this.host.hud.setScore('Поймано', formatScore(this.caught)); this.host.hud.setProgress('Цель', this.caught / 12, `${this.caught} / 12`); if (this.caught >= 12) { this.done = true; this.host.finish({ result: 'win', score: this.score, title: 'Мячик пойман!', message: 'Кот набегался и теперь гордо несёт мяч в зубах.', scoreLabel: 'очков', stats: [{ label: 'Поймано', value: '12 мячиков' }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#DDF5FF', '#FFE6C8'); drawPawPattern(ctx, this.w, this.h, 120, '#4FA8FF', 0.12); roundRect(ctx, 0, 620, this.w, 100, 0); shape(ctx, '#A7D477', null); ctx.fillStyle = '#FF6FA5'; ctx.beginPath(); ctx.arc(this.ballX, this.ballY, 22, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#2A1F17'; ctx.lineWidth = 4; ctx.stroke(); ctx.strokeStyle = '#FFF4E4'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(this.ballX - 5, this.ballY - 4, 8, 0.5, 4.6); ctx.stroke(); drawCat(ctx, { x: this.catX, y: this.catY, r: 39, t: this.t, mood: 'focus', legPhase: this.t * 9 }); }
  dispose(): void { }
}
export const ballCatGame: GameDefinition = { id: 'ball', path: '/game/ball', title: 'Кот за мячиком', tagline: 'Бегите за мячиком и ловите его лапками', description: 'Кот носится по двору за быстрым мячиком. Поймайте 12 раз.', emoji: '⚽', accent: '#3FC1A5', accentSoft: '#D8F5EA', goal: 'Цель: поймать 12 мячиков', rules: ['Ведите кота пальцем, мышью или стрелками.', 'Мяч отскакивает от стен.', 'Каждый пойманный мяч ускоряет игру.'], controls: 'Управление: палец · мышь · ← → · A / D · P — пауза · R — заново', bestSuffix: 'очков', pad: true, create: (host) => new BallCatGame(host) };
