import { audio } from '../core/audio';
import { drawCat, drawMilk, drawFish, drawSausage, drawSky, roundRect, shape } from '../core/draw';
import { formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';
interface Ingredient { kind: number; x: number; y: number; vy: number; }
class ChefCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private ingredients: Ingredient[] = []; private target = 0; private made = 0; private score = 0; private timer = .4; private catX = 240; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; host.hud.setScore('Блюда', '0'); host.hud.setProgress('Цель', 0, '0 / 10'); host.hud.setStatus('Собирай заказ'); host.input.onTap((x) => { this.catX = x; }); }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; const axis = this.host.input.axisX(); const p = this.host.input.pointer; if (axis) this.catX += axis * 300 * dt; else if (p.active) this.catX += (p.x - this.catX) * dt * 7; this.catX = Math.max(45, Math.min(this.w - 45, this.catX)); this.timer -= dt; if (this.timer <= 0) { this.ingredients.push({ kind: Math.floor(Math.random() * 3), x: rand(35, this.w - 35), y: -25, vy: rand(120, 180) }); this.timer = .7; } for (let i = this.ingredients.length - 1; i >= 0; i -= 1) { const item = this.ingredients[i]; if (!item) continue; item.y += item.vy * dt; if (Math.abs(item.x - this.catX) < 48 && item.y > 500) { this.ingredients.splice(i, 1); if (item.kind === this.target) { this.target = (this.target + 1) % 3; this.made += 1; this.score += 18; audio.play('eat'); this.host.hud.toast('Заказ готов!'); } else { this.target = 0; audio.play('bad'); this.host.hud.toast('Не тот ингредиент!', 'bad'); } } else if (item.y > this.h + 30) this.ingredients.splice(i, 1); } this.host.hud.setScore('Блюда', formatScore(this.made)); this.host.hud.setProgress('Цель', this.made / 10, `${this.made} / 10`); this.host.hud.setStatus(`Заказ: ${['рыбка', 'молоко', 'сосиска'][this.target] ?? 'рыбка'}`); if (this.made >= 10) { this.done = true; this.host.finish({ result: 'win', score: this.score, title: 'Кот-шеф открыл кафе!', message: 'Все заказы собраны в правильном порядке.', scoreLabel: 'очков', stats: [{ label: 'Блюд', value: '10' }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#FFF0D4', '#FFD7C7'); for (const item of this.ingredients) { if (item.kind === 0) drawFish(ctx, item.x, item.y, 20); else if (item.kind === 1) drawMilk(ctx, item.x, item.y, 22); else drawSausage(ctx, item.x, item.y, 23); } roundRect(ctx, 0, 620, this.w, 100, 0); shape(ctx, '#D9A96A', null); drawCat(ctx, { x: this.catX, y: 560, r: 40, t: this.t, mood: 'eat' }); roundRect(ctx, 25, 655, this.w - 50, 30, 15); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Лови ингредиенты по порядку заказа', this.w / 2, 675); }
  dispose(): void { this.ingredients = []; }
}
export const chefCatGame: GameDefinition = { id: 'chef', path: '/game/chef', title: 'Кот-повар', tagline: 'Собирайте ингредиенты для кошачьих заказов', description: 'Ловите рыбку, молоко и сосиску в правильном порядке, чтобы приготовить десять блюд.', emoji: '👨‍🍳', accent: '#FF7A2F', accentSoft: '#FFE2C9', goal: 'Цель: приготовить 10 блюд', rules: ['Порядок заказа написан справа.', 'Ловите ингредиенты котом.', 'Ошибка сбрасывает текущий заказ.'], controls: 'Управление: палец · мышь · ← → · A / D · P — пауза · R — заново', bestSuffix: 'очков', pad: true, create: (host) => new ChefCatGame(host) };
