import { audio } from '../core/audio';
import { drawCat, drawSky, roundRect, shape } from '../core/draw';
import { clamp, formatScore, rand } from '../core/math';
interface Platform { x: number; y: number; w: number; }
import type { GameDefinition, GameHost, GameInstance } from './types';
class ClimbCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private x = 240; private y = 560; private vy = -520; private height = 0; private platforms: Platform[] = []; private done = false; private t = 0;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; for (let i = 0; i < 10; i += 1) this.platforms.push({ x: rand(30, this.w - 130), y: 620 - i * 58, w: rand(90, 150) }); host.hud.setScore('Высота', '0 м'); host.hud.setProgress('Цель', 0, '0 / 180 м'); host.hud.setStatus('Лезь вверх'); }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; const axis = this.host.input.axisX(); const p = this.host.input.pointer; if (axis) this.x += axis * 300 * dt; else if (p.active) this.x += (p.x - this.x) * dt * 3; this.x = clamp(this.x, 25, this.w - 25); this.vy += 1250 * dt; this.y += this.vy * dt; for (const pl of this.platforms) pl.y += Math.max(0, -this.vy * dt * .15); for (const pl of this.platforms) if (this.vy > 0 && this.y > pl.y - 20 && this.y < pl.y + 18 && this.x > pl.x && this.x < pl.x + pl.w) { this.y = pl.y - 22; this.vy = -520; audio.play('jump'); } this.height += dt * 8; this.host.hud.setScore('Высота', `${formatScore(Math.floor(this.height))} м`); this.host.hud.setProgress('Цель', this.height / 180, `${Math.floor(this.height)} / 180 м`); if (this.height >= 180) { this.done = true; this.host.finish({ result: 'win', score: Math.floor(this.height), title: 'Кот забрался на крышу!', message: 'Высота покорена — сверху открывается отличный вид на миску.', scoreLabel: 'метров', stats: [{ label: 'Высота', value: '180 м' }] }); } else if (this.y > this.h + 50) { this.done = true; this.host.finish({ result: 'lose', score: Math.floor(this.height), title: 'Кот сорвался', message: 'Лапки устали. Попробуйте вести кота к платформам.', scoreLabel: 'метров', stats: [{ label: 'Высота', value: `${Math.floor(this.height)} м` }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#BFE5FF', '#FDF1D8'); for (const pl of this.platforms) { roundRect(ctx, pl.x, pl.y, pl.w, 14, 7); shape(ctx, '#7BCB8B', '#2A1F17', 3); } drawCat(ctx, { x: this.x, y: this.y, r: 30, t: this.t, mood: 'focus' }); }
  dispose(): void { this.platforms = []; }
}
export const climbCatGame: GameDefinition = { id: 'climb', path: '/game/climb', title: 'Лазилка', tagline: 'Ведите кота по уступам всё выше и выше', description: 'Кот прыгает по уступам и карабкается к крыше.', emoji: '🧗', accent: '#3FC1A5', accentSoft: '#D8F5EA', goal: 'Цель: забраться на 180 метров', rules: ['Ведите кота влево и вправо.', 'Приземляйтесь на зелёные платформы.', 'Поднимитесь на 180 метров.'], controls: 'Управление: палец · мышь · ← → · A / D · P — пауза · R — заново', bestSuffix: 'метров', pad: true, create: (host) => new ClimbCatGame(host) };
