import { audio } from '../core/audio';
import { drawCat, drawPawPattern, drawSky, drawFish, roundRect, shape } from '../core/draw';
import { formatScore } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';
class DigCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private tiles: boolean[] = Array(25).fill(false); private treasures: boolean[] = []; private found = 0; private score = 0; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; this.treasures = Array.from({ length: 25 }, (_, i) => i % 2 === 0 || i === 12); host.hud.setScore('Находки', '0'); host.hud.setProgress('Цель', 0, '0 / 10'); host.hud.setStatus('Копай землю'); host.input.onTap((x, y) => this.tap(x, y)); }
  private tap(x: number, y: number): void { const ox = 32; const oy = 150; const cell = Math.min(75, (this.w - 64) / 5); const c = Math.floor((x - ox) / cell); const r = Math.floor((y - oy) / cell); if (c < 0 || c >= 5 || r < 0 || r >= 5) return; const i = r * 5 + c; if (this.tiles[i]) return; this.tiles[i] = true; if (this.treasures[i]) { this.found += 1; this.score += 20; audio.play('pickup'); this.host.hud.toast('Нашёл рыбку!'); } else { audio.play('drop'); this.host.hud.toast('Только земля…', 'bad'); } }
  update(_dt: number, time: number): void { if (this.done) return; this.t = time; this.host.hud.setScore('Находки', formatScore(this.found)); this.host.hud.setProgress('Цель', this.found / 10, `${this.found} / 10`); if (this.found >= 10) { this.done = true; this.host.finish({ result: 'win', score: this.score, title: 'Клад найден!', message: 'Кот перекопал весь двор и нашёл запас вкусной рыбки.', scoreLabel: 'очков', stats: [{ label: 'Находок', value: '10' }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#FFE7C7', '#FFF4E4'); drawPawPattern(ctx, this.w, this.h, 120, '#C89262', .16); const cell = Math.min(75, (this.w - 64) / 5); for (let i = 0; i < 25; i += 1) { const c = i % 5; const r = Math.floor(i / 5); const x = 32 + c * cell; const y = 150 + r * cell; roundRect(ctx, x + 4, y + 4, cell - 8, cell - 8, 12); shape(ctx, this.tiles[i] ? '#B6D8AA' : '#B8784C', '#2A1F17', 3); if (this.tiles[i] && this.treasures[i]) drawFish(ctx, x + cell / 2, y + cell / 2, 18); } drawCat(ctx, { x: this.w / 2, y: 585, r: 35, t: this.t, mood: 'focus' }); }
  dispose(): void { }
}
export const digCatGame: GameDefinition = { id: 'dig', path: '/game/dig', title: 'Копалка кота', tagline: 'Копайте землю и ищите спрятанные вкусности', description: 'Тапайте по клеткам двора, чтобы найти десять спрятанных рыбок.', emoji: '⛏️', accent: '#C89262', accentSoft: '#F2D4B8', goal: 'Цель: найти 10 рыбок', rules: ['Тапайте по клеткам земли.', 'Голубые клетки скрывают находки.', 'Найдите 10 рыбок и закончите раскопки.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new DigCatGame(host) };
