import { audio } from '../core/audio';
import { drawCat, drawFish, drawPawPattern, roundRect, shape } from '../core/draw';
import { formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';
interface Fish { x: number; y: number; vx: number; caught: boolean; }
class FishingCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private fish: Fish[] = []; private score = 0; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; for (let i = 0; i < 9; i += 1) this.fish.push({ x: rand(35, this.w - 35), y: rand(180, 520), vx: rand(35, 80) * (Math.random() < .5 ? -1 : 1), caught: false }); host.hud.setScore('Рыбки', '0'); host.hud.setProgress('Цель', 0, '0 / 12'); host.hud.setStatus('Тапай по рыбкам'); host.input.onTap((x, y) => this.tap(x, y)); }
  private tap(x: number, y: number): void { const target = this.fish.find((f) => !f.caught && Math.hypot(f.x - x, f.y - y) < 34); if (!target) return; target.caught = true; this.score += 15; audio.play('eat'); this.host.hud.toast('Рыбка поймана!'); this.fish.push({ x: rand(35, this.w - 35), y: rand(180, 520), vx: rand(35, 80) * (Math.random() < .5 ? -1 : 1), caught: false }); }
  update(_dt: number, time: number): void { if (this.done) return; this.t = time; const caught = Math.floor(this.score / 15); this.fish.forEach((f) => { f.x += f.vx * _dt; if (f.x < 25 || f.x > this.w - 25) f.vx *= -1; }); this.host.hud.setScore('Рыбки', formatScore(caught)); this.host.hud.setProgress('Цель', caught / 12, `${caught} / 12`); if (caught >= 12) { this.done = true; this.host.finish({ result: 'win', score: this.score, title: 'Улов отличный!', message: 'Кот вытянул удочку и теперь ждёт ухи.', scoreLabel: 'очков', stats: [{ label: 'Рыбок', value: '12' }] }); } }
  render(ctx: CanvasRenderingContext2D): void { ctx.fillStyle = '#A8DFF5'; ctx.fillRect(0, 0, this.w, this.h); drawPawPattern(ctx, this.w, this.h, 120, '#FFFFFF', .12); ctx.fillStyle = '#4B9BC5'; ctx.fillRect(0, 120, this.w, this.h - 120); for (const f of this.fish) if (!f.caught) drawFish(ctx, f.x, f.y + Math.sin(this.t * 3 + f.x) * 5, 20, f.vx < 0 ? Math.PI : 0); ctx.strokeStyle = '#C88B55'; ctx.lineWidth = 5; ctx.beginPath(); ctx.moveTo(this.w / 2, 585); ctx.lineTo(this.w / 2 + 50, 250); ctx.stroke(); drawCat(ctx, { x: this.w / 2, y: 580, r: 38, t: this.t, mood: 'focus' }); roundRect(ctx, 24, 655, this.w - 48, 30, 15); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Тапай по рыбкам в пруду', this.w / 2, 675); }
  dispose(): void { this.fish = []; }
}
export const fishingCatGame: GameDefinition = { id: 'fishing', path: '/game/fishing', title: 'Кот-рыбак', tagline: 'Ловите рыбок в пруду одной лапкой', description: 'Рыбки плавают в пруду. Тапайте по ним, пока кот держит удочку.', emoji: '🎣', accent: '#4FA8FF', accentSoft: '#DDF2FF', goal: 'Цель: поймать 12 рыбок', rules: ['Тапайте по рыбкам в воде.', 'Рыбки плавают в разные стороны.', 'Поймайте 12 рыбок для победы.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new FishingCatGame(host) };
