import { audio } from '../core/audio';
import { drawCat, drawPawPattern, drawSky, roundRect, shape } from '../core/draw';
import { formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';

interface Flower { x: number; y: number; water: number; phase: number }
class GardenCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private flowers: Flower[] = []; private water = 100; private score = 0; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; for (let i = 0; i < 8; i += 1) this.flowers.push({ x: 55 + (i % 4) * 122, y: 220 + Math.floor(i / 4) * 150, water: rand(0, 0.32), phase: rand(0, 6) }); host.hud.setScore('Цветы', '0'); host.hud.setProgress('Цель', 0, '0 / 8'); host.hud.setStatus('Поливай цветы'); host.input.onTap((x, y) => this.tap(x, y)); }
  private tap(x: number, y: number): void { const flower = this.flowers.find((f) => Math.hypot(f.x - x, f.y - y) < 48 && f.water < 1); if (!flower || this.water <= 0) return; flower.water = Math.min(1, flower.water + 0.24); this.water -= 2; audio.play('splash'); this.host.hud.toast(flower.water >= 1 ? 'Расцвёл!' : 'Ещё капельку'); if (flower.water >= 1) this.score += 20; }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; this.water = Math.min(100, this.water + dt * 1.4); const ready = this.flowers.filter((f) => f.water >= 1).length; this.host.hud.setScore('Цветы', formatScore(ready)); this.host.hud.setProgress('Цель', ready / 8, `${ready} / 8`); this.host.hud.setStatus(`💧 ${Math.floor(this.water)}%`, this.water < 15 ? 'bad' : 'neutral'); if (ready >= 8) { this.done = true; audio.play('win'); this.host.finish({ result: 'win', score: this.score, title: 'Сад расцвёл!', message: 'Кот полил всё до последнего ростка и теперь нюхает розы.', scoreLabel: 'очков', stats: [{ label: 'Цветов', value: '8' }, { label: 'Осталось воды', value: `${Math.floor(this.water)}%` }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#DDF6E8', '#FFF4D7'); drawPawPattern(ctx, this.w, this.h, 150, '#7FC97F', 0.15); roundRect(ctx, 0, 610, this.w, 110, 0); shape(ctx, '#8FCB7B', null); for (const f of this.flowers) { const sway = Math.sin(this.t * 2 + f.phase) * 3; ctx.strokeStyle = '#32734D'; ctx.lineWidth = 7; ctx.beginPath(); ctx.moveTo(f.x, f.y + 42); ctx.lineTo(f.x + sway, f.y); ctx.stroke(); ctx.fillStyle = f.water >= 1 ? '#FF6FA5' : '#B8A982'; ctx.beginPath(); ctx.arc(f.x + sway, f.y - 5, 22 + f.water * 5, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#2A1F17'; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = '#FFD45A'; ctx.beginPath(); ctx.arc(f.x + sway, f.y - 5, 7, 0, Math.PI * 2); ctx.fill(); roundRect(ctx, f.x - 30, f.y + 55, 60, 8, 4); shape(ctx, '#FFFFFF', '#2A1F17', 2); roundRect(ctx, f.x - 30, f.y + 55, 60 * f.water, 8, 4); shape(ctx, '#4FA8FF', null); } drawCat(ctx, { x: 240, y: 585, r: 34, t: this.t, mood: 'happy' }); }
  dispose(): void { this.flowers = []; }
}
export const gardenCatGame: GameDefinition = { id: 'garden', path: '/game/garden', title: 'Кот-садовник', tagline: 'Поливайте цветы и вырастите маленький сад', description: 'В каждом цветке спрятан росток. Тапайте по клумбам, чтобы полить все восемь цветов.', emoji: '🌷', accent: '#3FC1A5', accentSoft: '#D8F5EA', goal: 'Цель: вырастить 8 цветов', rules: ['Тапайте по цветам, чтобы поливать их.', 'Запас воды постепенно восстанавливается.', 'Вырастите все 8 цветов и получите садовый рекорд.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new GardenCatGame(host) };
