import { audio } from '../core/audio';
import { drawCat, drawPawPattern, drawSky, roundRect, shape } from '../core/draw';
import { clamp, formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';

class HideSeekGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number;
  private x = 120; private y = 280; private vx = 150; private timer = 1.2; private found = 0; private score = 0; private timeLeft = 40; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; host.hud.setScore('Найдено', '0'); host.hud.setProgress('Цель', 0, '0 / 15'); host.hud.setStatus('Лови бегущего кота'); host.input.onTap((x, y) => this.tap(x, y)); }
  private move(): void { this.x = rand(65, this.w - 65); this.y = rand(170, 450); this.vx = (Math.random() < 0.5 ? -1 : 1) * rand(130, 220); this.timer = Math.max(0.65, 1.25 - this.found * 0.025); }
  private tap(x: number, y: number): void { if (Math.hypot(x - this.x, y - this.y) < 65) { this.found += 1; this.score += 15; audio.play('pickup'); this.host.hud.toast('Поймал бегущего кота!'); this.move(); } else { this.host.hud.toast('Мимо хвоста…', 'bad'); audio.play('bad'); } }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; this.timeLeft -= dt; this.timer -= dt; this.x += this.vx * dt; this.y += Math.sin(time * 3) * 20 * dt; if (this.x < 55 || this.x > this.w - 55) this.vx *= -1; this.x = clamp(this.x, 55, this.w - 55); if (this.timer <= 0) this.move(); this.host.hud.setScore('Найдено', formatScore(this.found)); this.host.hud.setProgress('Цель', this.found / 15, `${this.found} / 15`); this.host.hud.setStatus(`⏱ ${Math.ceil(Math.max(0, this.timeLeft))} с`, this.timeLeft < 8 ? 'bad' : 'neutral'); if (this.found >= 15) { this.done = true; audio.play('win'); this.host.finish({ result: 'win', score: this.score, title: 'Все коты пойманы!', message: 'Кот бегал сверху по площадке, но ты оказался быстрее.', scoreLabel: 'очков', stats: [{ label: 'Найдено', value: '15 котов' }] }); } else if (this.timeLeft <= 0) { this.done = true; audio.play('lose'); this.host.finish({ result: 'lose', score: this.score, title: 'Кот убежал', message: 'Он всё время был на виду — просто слишком быстро бегал.', scoreLabel: 'очков', stats: [{ label: 'Поймано', value: `${this.found} / 15` }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#D9F0FF', '#FFF4D7'); drawPawPattern(ctx, this.w, this.h, 105, '#4FA8FF', 0.13); roundRect(ctx, 25, 150, this.w - 50, 410, 22); shape(ctx, '#BFE2F0', '#2A1F17', 4); ctx.fillStyle = '#7CB66B'; ctx.fillRect(25, 520, this.w - 50, 40); ctx.strokeStyle = '#FFFFFF'; ctx.lineWidth = 4; ctx.setLineDash([16, 14]); ctx.beginPath(); ctx.moveTo(50, 520); ctx.lineTo(this.w - 50, 520); ctx.stroke(); ctx.setLineDash([]); drawCat(ctx, { x: this.x, y: this.y, r: 34, t: this.t, mood: 'focus', legPhase: this.t * 8, tilt: Math.sin(this.t * 8) * 0.08 }); roundRect(ctx, 22, 655, this.w - 44, 30, 15); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Кот бегает сверху — тапни по нему', this.w / 2, 675); }
  dispose(): void { }
}
export const hideSeekGame: GameDefinition = { id: 'hide', path: '/game/hide', title: 'Где кот?', tagline: 'Ловите кота, который бегает сверху по площадке', description: 'Кот больше не прячется под коробками — он носится по площадке. Поймайте его 15 раз.', emoji: '🐈‍⬛', accent: '#FFC94A', accentSoft: '#FFF0B9', goal: 'Цель: поймать 15 котов', rules: ['Кот всегда виден и бегает по площадке.', 'Тапайте по нему, пока он не сменил направление.', 'Поймайте 15 котов за 40 секунд.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new HideSeekGame(host) };
