import { audio } from '../core/audio';
import { drawCat, drawPawPattern, drawSky, roundRect, shape } from '../core/draw';
import { formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';

class HideSeekGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private x = 240; private y = 260; private timer = 1; private found = 0; private score = 0; private timeLeft = 40; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; host.hud.setScore('Найдено', '0'); host.hud.setProgress('Цель', 0, '0 / 15'); host.hud.setStatus('Ищи кота'); host.input.onTap((x, y) => this.tap(x, y)); }
  private move(): void { this.x = rand(65, this.w - 65); this.y = rand(145, 540); this.timer = Math.max(0.55, 1.25 - this.found * 0.025); }
  private tap(x: number, y: number): void { if (Math.hypot(x - this.x, y - this.y) < 58) { this.found += 1; this.score += 15; audio.play('pickup'); this.host.hud.toast('Нашёлся!'); this.move(); } else { this.host.hud.toast('Пусто…', 'bad'); audio.play('bad'); } }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; this.timeLeft -= dt; this.timer -= dt; if (this.timer <= 0) this.move(); this.host.hud.setScore('Найдено', formatScore(this.found)); this.host.hud.setProgress('Цель', this.found / 15, `${this.found} / 15`); this.host.hud.setStatus(`⏱ ${Math.ceil(Math.max(0, this.timeLeft))} с`, this.timeLeft < 8 ? 'bad' : 'neutral'); if (this.found >= 15) { this.done = true; audio.play('win'); this.host.finish({ result: 'win', score: this.score, title: 'Все коты найдены!', message: 'Коты вылезли из своих укрытий и требуют лакомство.', scoreLabel: 'очков', stats: [{ label: 'Найдено', value: '15 котов' }] }); } else if (this.timeLeft <= 0) { this.done = true; audio.play('lose'); this.host.finish({ result: 'lose', score: this.score, title: 'Коты спрятались', message: 'Некоторые хвосты ещё шуршат за занавеской.', scoreLabel: 'очков', stats: [{ label: 'Найдено', value: `${this.found} / 15` }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#FFE3BD', '#FFF8E8'); drawPawPattern(ctx, this.w, this.h, 105, '#E0A25E', 0.2); for (const [x, y, r] of [[85, 180, 42], [390, 230, 55], [115, 470, 50], [370, 520, 45]] as const) { roundRect(ctx, x - r, y - r, r * 2, r * 2, 16); shape(ctx, '#D98A55', '#2A1F17', 3); } ctx.save(); ctx.globalAlpha = Math.min(1, this.timer * 3); drawCat(ctx, { x: this.x, y: this.y, r: 33, t: this.t, mood: 'blink' }); ctx.restore(); roundRect(ctx, 22, 655, this.w - 44, 30, 15); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Тапни по коту, пока он не сменил укрытие', this.w / 2, 675); }
  dispose(): void { }
}
export const hideSeekGame: GameDefinition = { id: 'hide', path: '/game/hide', title: 'Где кот?', tagline: 'Ищите хитрого кота, пока он меняет укрытия', description: 'Кот выглядывает в случайных местах. Найдите его 15 раз за 40 секунд.', emoji: '🕵️', accent: '#FFC94A', accentSoft: '#FFF0B9', goal: 'Цель: найти 15 котов', rules: ['Тапайте по выглядывающему коту.', 'Кот меняет место, если его не нашли вовремя.', 'Промах не отнимает очки, но сбивает ритм.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new HideSeekGame(host) };
