import { audio } from '../core/audio';
import { drawCat, drawPawPattern, drawSky, roundRect, shape } from '../core/draw';
import { formatScore } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';
class JumpRopeCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private phase = 0; private jumping = 0; private jumps = 0; private fails = 3; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; host.hud.setScore('Прыжки', '0'); host.hud.setProgress('Цель', 0, '0 / 20'); host.hud.setStatus('Прыгай через верёвку'); host.input.onTap(() => { if (this.jumping <= 0) { this.jumping = .62; audio.play('jump'); } }); }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; this.phase += dt * 4; this.jumping = Math.max(0, this.jumping - dt); const ropeY = 565 + Math.sin(this.phase) * 55; if (ropeY < 535 && this.jumping <= 0) { this.fails -= 1; audio.play('bad'); this.host.hud.toast('Прыгни выше!', 'bad'); this.phase += .45; } if (Math.sin(this.phase) > .98) { this.jumps += 1; audio.play('land'); } this.jumps = Math.min(20, this.jumps); this.host.hud.setScore('Прыжки', formatScore(this.jumps)); this.host.hud.setProgress('Цель', this.jumps / 20, `${this.jumps} / 20`); this.host.hud.setStatus(`Ошибки: ${this.fails}`, this.fails <= 1 ? 'bad' : 'neutral'); if (this.jumps >= 20) { this.done = true; this.host.finish({ result: 'win', score: this.jumps * 10, title: 'Кот-прыгун чемпион!', message: 'Двадцать прыжков подряд — верёвка капитулировала.', scoreLabel: 'очков', stats: [{ label: 'Прыжков', value: '20' }] }); } else if (this.fails <= 0) { this.done = true; this.host.finish({ result: 'lose', score: this.jumps * 10, title: 'Верёвка победила', message: 'Ритм сбился. Попробуйте нажимать чуть раньше.', scoreLabel: 'очков', stats: [{ label: 'Прыжков', value: `${this.jumps}` }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#FFE8F1', '#FFF5D6'); drawPawPattern(ctx, this.w, this.h, 120, '#FF6FA5', .12); const lift = this.jumping > 0 ? Math.sin((this.jumping / .62) * Math.PI) * 80 : 0; drawCat(ctx, { x: this.w / 2, y: 555 - lift, r: 40, t: this.t, mood: 'happy' }); ctx.strokeStyle = '#9B8CFF'; ctx.lineWidth = 8; ctx.beginPath(); ctx.moveTo(35, 570 + Math.sin(this.phase) * 55); ctx.quadraticCurveTo(this.w / 2, 480 - Math.sin(this.phase) * 55, this.w - 35, 570 + Math.sin(this.phase) * 55); ctx.stroke(); roundRect(ctx, 25, 655, this.w - 50, 30, 15); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Тапай в ритм и перепрыгивай верёвку', this.w / 2, 675); }
  dispose(): void { }
}
export const jumpRopeCatGame: GameDefinition = { id: 'rope', path: '/game/rope', title: 'Прыгалка', tagline: 'Прыгайте через верёвку в ритм', description: 'Тапайте, когда верёвка приближается к лапкам. Сделайте двадцать прыжков.', emoji: '🪢', accent: '#FF6FA5', accentSoft: '#FFE0EC', goal: 'Цель: сделать 20 прыжков', rules: ['Тап — прыжок.', 'Следите за ритмом верёвки.', 'Три ошибки заканчивают партию.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new JumpRopeCatGame(host) };
