import { audio } from '../core/audio';
import { drawCat, drawPawPattern, drawSky, roundRect, shape } from '../core/draw';
import { formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';

class LaserCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number;
  private x = 240; private y = 300; private vx = 170; private vy = 130; private hits = 0; private score = 0; private lives = 5; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; host.hud.setScore('Попадания', '0'); host.hud.setProgress('Цель', 0, '0 / 15'); host.hud.setStatus('Тапни по лазеру'); host.input.onTap((x, y) => this.tap(x, y)); }
  private tap(x: number, y: number): void { if (Math.hypot(x - this.x, y - this.y) < 34) { this.hits += 1; this.score += 15; audio.play('pickup'); this.host.hud.toast('Поймал красную точку!'); this.x = rand(45, this.w - 45); this.y = rand(120, 570); this.vx *= 1.04; this.vy *= 1.04; } else { this.lives -= 1; audio.play('bad'); this.host.shake(4); this.host.hud.toast('Мимо!', 'bad'); } }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; this.x += this.vx * dt; this.y += this.vy * dt; if (this.x < 35 || this.x > this.w - 35) this.vx *= -1; if (this.y < 110 || this.y > 585) this.vy *= -1; this.host.hud.setScore('Попадания', formatScore(this.hits)); this.host.hud.setProgress('Цель', this.hits / 15, `${this.hits} / 15`); this.host.hud.setStatus(`Жизни: ${this.lives}`, this.lives <= 1 ? 'bad' : 'neutral'); if (this.hits >= 15) { this.done = true; audio.play('win'); this.host.finish({ result: 'win', score: this.score, title: 'Лазер пойман!', message: 'Кот победил самую быструю красную точку в доме.', scoreLabel: 'очков', stats: [{ label: 'Точность', value: `${this.hits} попаданий` }] }); } else if (this.lives <= 0) { this.done = true; audio.play('lose'); this.host.finish({ result: 'lose', score: this.score, title: 'Лазер убежал', message: 'Красная точка оказалась слишком юркой.', scoreLabel: 'очков', stats: [{ label: 'Попадания', value: `${this.hits} / 15` }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#29203D', '#604B7C'); drawPawPattern(ctx, this.w, this.h, 110, '#FFFFFF', 0.08); ctx.save(); ctx.shadowColor = '#FF4B70'; ctx.shadowBlur = 22; ctx.fillStyle = '#FF496B'; ctx.beginPath(); ctx.arc(this.x, this.y, 13 + Math.sin(this.t * 8) * 2, 0, Math.PI * 2); ctx.fill(); ctx.restore(); drawCat(ctx, { x: this.w / 2, y: 620, r: 38, t: this.t, mood: 'focus' }); roundRect(ctx, 20, 660, this.w - 40, 28, 14); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Тапай по красной точке · промах отнимает жизнь', this.w / 2, 679); }
  dispose(): void { }
}
export const laserCatGame: GameDefinition = { id: 'laser', path: '/game/laser', title: 'Лазерный кот', tagline: 'Поймайте красную точку, пока она носится по комнате', description: 'Красная точка летает по экрану. Попадите по ней 15 раз, сохранив пять жизней.', emoji: '🔴', accent: '#9B8CFF', accentSoft: '#E7E2FF', goal: 'Цель: 15 попаданий', rules: ['Тапайте прямо по красной точке.', 'Промах отнимает одну жизнь.', 'С каждым попаданием точка ускоряется.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new LaserCatGame(host) };
