import { audio } from '../core/audio';
import { drawCat, drawSky, roundRect, shape } from '../core/draw';
import { formatScore, randInt } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';
const COLORS = ['#FFB877', '#9B8CFF', '#5AA9E6', '#3FC1A5', '#FF6FA5'];
class MatchCatsGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private readonly cols = 6; private readonly rows = 7; private readonly cell = 68; private grid: number[] = []; private score = 0; private selected = -1; private turns = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; this.grid = Array.from({ length: this.cols * this.rows }, () => randInt(0, COLORS.length - 1)); host.hud.setScore('Очки', '0'); host.hud.setProgress('Цель', 0, '0 / 12'); host.hud.setStatus('Собери тройки'); host.input.onTap((x, y) => this.tap(x, y)); }
  private tap(x: number, y: number): void { const ox = (this.w - this.cols * this.cell) / 2; const oy = 95; const c = Math.floor((x - ox) / this.cell); const r = Math.floor((y - oy) / this.cell); if (c < 0 || c >= this.cols || r < 0 || r >= this.rows) return; const idx = r * this.cols + c; if (this.selected < 0) { this.selected = idx; return; } if (Math.abs((this.selected % this.cols) - c) + Math.abs(Math.floor(this.selected / this.cols) - r) !== 1) { this.selected = idx; return; } const old = this.grid[idx]; this.grid[idx] = this.grid[this.selected] ?? 0; this.grid[this.selected] = old ?? 0; this.selected = -1; this.turns += 1; const matches = new Set<number>(); for (let row = 0; row < this.rows; row += 1) for (let col = 0; col < this.cols - 2; col += 1) { const a = row * this.cols + col; if (this.grid[a] === this.grid[a + 1] && this.grid[a] === this.grid[a + 2]) [a, a + 1, a + 2].forEach((i) => matches.add(i)); } for (let col = 0; col < this.cols; col += 1) for (let row = 0; row < this.rows - 2; row += 1) { const a = row * this.cols + col; if (this.grid[a] === this.grid[a + this.cols] && this.grid[a] === this.grid[a + this.cols * 2]) [a, a + this.cols, a + this.cols * 2].forEach((i) => matches.add(i)); } if (matches.size) { this.score += matches.size * 10; audio.play('combo'); this.host.hud.toast(`Тройка! +${matches.size * 10}`); matches.forEach((i) => { this.grid[i] = randInt(0, COLORS.length - 1); }); } }
  update(_dt: number, _time: number): void { if (this.done) return; const groups = Math.floor(this.score / 30); this.host.hud.setScore('Очки', formatScore(this.score)); this.host.hud.setProgress('Цель', groups / 12, `${groups} / 12`); if (groups >= 12) { this.done = true; this.host.finish({ result: 'win', score: this.score, title: 'Кошачий ряд собран!', message: 'Три одинаковых кота подряд — и вся доска мурчит.', scoreLabel: 'очков', stats: [{ label: 'Троек', value: '12' }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#FFF2D8', '#E4DEFF'); const ox = (this.w - this.cols * this.cell) / 2; const oy = 95; for (let i = 0; i < this.grid.length; i += 1) { const c = i % this.cols; const r = Math.floor(i / this.cols); roundRect(ctx, ox + c * this.cell + 3, oy + r * this.cell + 3, this.cell - 6, this.cell - 6, 14); shape(ctx, COLORS[this.grid[i] ?? 0], '#2A1F17', this.selected === i ? 6 : 3); drawCat(ctx, { x: ox + c * this.cell + this.cell / 2, y: oy + r * this.cell + 35, r: 15, body: false, mood: 'happy' }); } }
  dispose(): void { this.grid = []; }
}
export const matchCatsGame: GameDefinition = { id: 'match', path: '/game/match', title: 'Три кота в ряд', tagline: 'Собирайте тройки одинаковых котов', description: 'Меняйте соседние плитки местами и собирайте горизонтальные и вертикальные тройки.', emoji: '🐱', accent: '#FFC94A', accentSoft: '#FFF0B9', goal: 'Цель: собрать 12 троек', rules: ['Выберите кота и соседнюю плитку.', 'Тройка по горизонтали или вертикали даёт очки.', 'Соберите 12 троек для победы.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new MatchCatsGame(host) };
