import { audio } from '../core/audio';
import { drawBubble, drawCat, drawSky, roundRect, shape } from '../core/draw';
import { formatScore, rand } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';
interface Balloon { x: number; y: number; r: number; popped: boolean }
class RayCatGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private balloons: Balloon[] = []; private score = 0; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; for (let i = 0; i < 16; i += 1) this.balloons.push({ x: rand(36, this.w - 36), y: 120 + (i % 4) * 95, r: 25, popped: false }); host.hud.setScore('Шарики', '0'); host.hud.setProgress('Цель', 0, '0 / 16'); host.hud.setStatus('Тапай по шарикам'); host.input.onTap((x, y) => this.pop(x, y)); }
  private pop(x: number, y: number): void { const target = this.balloons.find((b) => !b.popped && Math.hypot(b.x - x, b.y - y) < b.r + 15); if (!target) return; target.popped = true; this.score += 15; audio.play('pickup'); this.host.hud.toast('Луч попал!'); }
  update(_dt: number, time: number): void { if (this.done) return; this.t = time; const popped = this.balloons.filter((b) => b.popped).length; this.host.hud.setScore('Шарики', formatScore(popped)); this.host.hud.setProgress('Цель', popped / 16, `${popped} / 16`); if (popped >= 16) { this.done = true; audio.play('win'); this.host.finish({ result: 'win', score: this.score, title: 'Шарики лопнули!', message: 'Кот включил лазерный взгляд и спас потолок от воздушного праздника.', scoreLabel: 'очков', stats: [{ label: 'Шариков', value: '16' }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#10192C', '#4C3B72'); for (const b of this.balloons) if (!b.popped) drawBubble(ctx, b.x, b.y + Math.sin(this.t * 2 + b.x) * 5, b.r, 0.9); const catY = 585; drawCat(ctx, { x: this.w / 2, y: catY, r: 42, t: this.t, mood: 'focus' }); ctx.save(); ctx.strokeStyle = '#FF4F72'; ctx.shadowColor = '#FF4F72'; ctx.shadowBlur = 16; ctx.lineWidth = 6; for (const ex of [-15, 15]) { ctx.beginPath(); ctx.moveTo(this.w / 2 + ex, catY - 12); ctx.lineTo(this.w / 2 + ex * 3, 85); ctx.stroke(); } ctx.restore(); roundRect(ctx, 25, 655, this.w - 50, 30, 15); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Лучи из глаз лопают шарики сверху', this.w / 2, 675); }
  dispose(): void { this.balloons = []; }
}
export const rayCatGame: GameDefinition = { id: 'ray', path: '/game/ray', title: 'Кот-лазер', tagline: 'Лучи из глаз лопают шарики сверху', description: 'Тапайте по шарикам, а кот будет бить по ним лазерным взглядом.', emoji: '⚡', accent: '#FF6FA5', accentSoft: '#FFE0EC', goal: 'Цель: лопнуть 16 шариков', rules: ['Тапайте по шарикам над котом.', 'Луч из глаз автоматически показывает попадание.', 'Лопните всё поле для победы.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new RayCatGame(host) };
