import { audio } from '../core/audio';
import { drawCat, drawSky, roundRect, shape } from '../core/draw';
import { formatScore, randInt } from '../core/math';
import type { GameDefinition, GameHost, GameInstance } from './types';
const COLORS = ['#FF6FA5', '#5AA9E6', '#FFC94A', '#3FC1A5'];
interface Ball { x: number; y: number; color: number; }
class ZumaCatsGame implements GameInstance {
  private readonly host: GameHost; private readonly w: number; private readonly h: number; private balls: Ball[] = []; private shot = 0; private score = 0; private t = 0; private done = false;
  constructor(host: GameHost) { this.host = host; this.w = host.world.w; this.h = host.world.h; for (let i = 0; i < 22; i += 1) this.balls.push({ x: 55 + i * 27, y: 280 + Math.sin(i * 0.65) * 70, color: randInt(0, COLORS.length - 1) }); host.hud.setScore('Лопнуто', '0'); host.hud.setProgress('Цель', 0, '0 / 20'); host.hud.setStatus('Лови цветные цепочки'); host.input.onTap((x, y) => this.shoot(x, y)); }
  private shoot(x: number, y: number): void { const target = this.balls.find((b) => Math.hypot(b.x - x, b.y - y) < 30); if (!target) return; const color = target.color; const same = this.balls.filter((b) => b.color === color && Math.abs(b.x - target.x) < 75); if (same.length < 2) { this.shot = (this.shot + 1) % COLORS.length; this.host.hud.toast('Нужна цепочка из двух!', 'bad'); return; } this.balls = this.balls.filter((b) => !(b.color === color && Math.abs(b.x - target.x) < 75)); this.score += same.length * 10; audio.play('combo'); this.host.hud.toast(`Цепочка ×${same.length}`); }
  update(dt: number, time: number): void { if (this.done) return; this.t = time; for (const b of this.balls) b.x -= dt * 17; if (this.balls.some((b) => b.x < 35)) { this.done = true; this.host.finish({ result: 'lose', score: this.score, title: 'Цепочка дошла до домика', message: 'Стреляйте по соседним котошарикам быстрее.', scoreLabel: 'очков', stats: [{ label: 'Лопнуто', value: `${Math.floor(this.score / 10)}` }] }); return; } const popped = Math.floor(this.score / 10); this.host.hud.setScore('Лопнуто', formatScore(popped)); this.host.hud.setProgress('Цель', popped / 20, `${popped} / 20`); if (popped >= 20) { this.done = true; this.host.finish({ result: 'win', score: this.score, title: 'Котошарики спасены!', message: 'Цветная цепочка рассыпалась до того, как добралась до домика.', scoreLabel: 'очков', stats: [{ label: 'Лопнуто', value: '20' }] }); } }
  render(ctx: CanvasRenderingContext2D): void { drawSky(ctx, this.w, this.h, '#DCEBFF', '#FFE3EF'); ctx.fillStyle = '#8D6B9B'; ctx.fillRect(30, 240, this.w - 60, 150); for (const b of this.balls) { ctx.fillStyle = COLORS[b.color] ?? COLORS[0]; ctx.beginPath(); ctx.arc(b.x, b.y, 20, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#2A1F17'; ctx.lineWidth = 3; ctx.stroke(); drawCat(ctx, { x: b.x, y: b.y + 6, r: 12, body: false, mood: 'happy' }); } drawCat(ctx, { x: this.w / 2, y: 570, r: 38, t: this.t, mood: 'focus' }); roundRect(ctx, 24, 655, this.w - 48, 30, 15); shape(ctx, '#FFF6E4', '#2A1F17', 3); ctx.fillStyle = '#2A1F17'; ctx.font = '600 17px Nunito, system-ui'; ctx.textAlign = 'center'; ctx.fillText('Тапай по соседним котошарикам одного цвета', this.w / 2, 675); }
  dispose(): void { this.balls = []; }
}
export const zumaCatsGame: GameDefinition = { id: 'zuma', path: '/game/zuma', title: 'Зума с котами', tagline: 'Лопайте цепочки котошариков до домика', description: 'Цветные котошарики движутся к домику. Собирайте соседние цепочки одного цвета.', emoji: '🟣', accent: '#5AA9E6', accentSoft: '#DDF0FF', goal: 'Цель: лопнуть 20 котошариков', rules: ['Тапните по котошарику в цепочке.', 'Цветные соседи лопаются вместе.', 'Не дайте цепочке дойти до домика.'], controls: 'Управление: тап · клик · P — пауза · R — заново', bestSuffix: 'очков', create: (host) => new ZumaCatsGame(host) };
